name: Build AU Plugin (macOS)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install pkg-config

      - name: Build Audio Unit with Xcode
        run: |
          cd Builds/MacOSX
          xcodebuild -project DissonanceMeeter.xcodeproj -configuration Release -arch x86_64

      - name: Upload AU component
        uses: actions/upload-artifact@v4
        with:
          name: AU-Build
          path: Builds/MacOSX/build/Release/*.component
